wordpress:
  build: .
  links:
    - wordpress_db:mysql
    - maildev:maildev
  ports:
    - 8080:80

realskeptic_db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: examplepass

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links:
    - wordpress_db:db
  ports:
    - 8181:80
  environment:
    PMA_USER: root
    PMA_PASSWORD: examplepass

maildev:
  image: djfarrelly/maildev
  ports:
   - 8282:80
